apiVersion: v1
kind: ReplicationController
metadata:
  name: "cadvisor-signalfx"
spec:
  replicas: 1
  selector:
    app: "cadvisor-signalfx"
  template:
    metadata:
      name: "cadvisor-signalfx"
      labels:
        app: "cadvisor-signalfx"
    spec:
      containers:
      - name: "cadvisor-signalfx"
        image: "quay.io/signalfx/cadvisor-integration:latest"
        env:
        - name: SFX_SCRAPPER_API_TOKEN
          value: rxAICXyz-n7FuVOzIvFVww
        - name: SFX_SCRAPPER_CLUSTER_NAME
          value: gke-guestbook-default-pool-845a05c5-f2xk
        - name: SFX_SCRAPPER_SEND_RATE
          value: 5s
        - name: SFX_SCRAPPER_CADVISOR_PORT
          value: 4194
